### ISSUE TITLE
UI doesnt load in 172&java7

### ISSUE THREAD

**Issue by WeAthFoLD** [LambdaInnovation/Dawn47#1]
```
[12:06:59] [Client thread/FATAL] [AnnotationRegistry]: Error on loading class cn.dawn47.equipment.client.gui.HudGui. Please check the implementation.
java.lang.NoSuchMethodError: java.util.List.sort(Ljava/util/Comparator;)V
    at cn.liutils.vis.animation.LineInterpCurve.addPoint(LineInterpCurve.java:31)
    at cn.dawn47.equipment.client.gui.HudGui.<init>(HudGui.java:95)
    at cn.dawn47.equipment.client.gui.HudGui.<clinit>(HudGui.java:77)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cn.annoreg.core.RegistrationManager.loadClasses(RegistrationManager.java:54)
    at cn.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:156)
    at cn.annoreg.core.RegistrationManager.registerAll(RegistrationManager.java:167)
    at cn.dawn47.Dawn47.preInit(Dawn47.java:89)
```

**Comment by WeAthFoLD** [comment]
fixed via LambdaLib.
